alter session set container = XEPDB1;

--DROP SEQUENCE SMOOTHNESS_OWNER.MOVIE_ID;
--DROP TABLE SMOOTHNESS_OWNER.MOVIE CASCADE CONSTRAINTS PURGE;

CREATE SEQUENCE SMOOTHNESS_OWNER.MOVIE_ID;

CREATE TABLE SMOOTHNESS_OWNER.MOVIE
(
    MOVIE_ID             INTEGER NOT NULL ,
    TITLE                VARCHAR2(128 CHAR) NULL ,
    RELEASE_DATE         DATE NULL ,
    DESCRIPTION          VARCHAR2(512 CHAR) NULL ,
    MPAA_RATING          VARCHAR2(5 CHAR) NULL  CONSTRAINT  MOVIE_CK1 CHECK (MPAA_RATING IN ('G', 'PG', 'PG-13', 'R', 'NC-17')),
    DURATION_MINUTES     INTEGER NULL ,
    CONSTRAINT  MOVIE_PK PRIMARY KEY (MOVIE_ID)
);

CREATE TABLE SMOOTHNESS_OWNER.SETTING
(
    KEY                VARCHAR2(128 CHAR)  NOT NULL,
    VALUE              VARCHAR2(4000 BYTE) NOT NULL,
    TYPE               VARCHAR2(32 CHAR) DEFAULT 'STRING' NOT NULL,
    DESCRIPTION        VARCHAR2(2048 CHAR) NOT NULL,
    TAG                VARCHAR2(32 CHAR) DEFAULT 'OTHER' NOT NULL,
    WEIGHT             INTEGER DEFAULT 0 NOT NULL,
    CHANGE_ACTION_JNDI VARCHAR2(128 CHAR) NULL ,
    CONSTRAINT SETTING_PK PRIMARY KEY (KEY),
    CONSTRAINT SETTING_CK1 CHECK (TYPE IN ('STRING', 'BOOLEAN', 'CSV')),
    CONSTRAINT SETTING_CK2 CHECK ((VALUE in ('Y', 'N') AND TYPE = 'BOOLEAN') OR TYPE <> 'BOOLEAN')
);