services:
  oracle:
    extends:
      file: compose.yaml
      service: oracle

  keycloak:
    extends:
      file: compose.yaml
      service: keycloak

  puppet:
    extends:
      file: compose.yaml
      service: puppet

  mailhog:
    extends:
      file: compose.yaml
      service: mailhog

  demo:
    extends:
      file: compose.yaml
      service: demo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt
    pull_policy: never