---
version: '3.9'

services:
  oracle:
    extends:
      file: docker-compose.yml
      service: oracle
    volumes:
      - ./run/oracle/oradata:/opt/oracle/oradata

  keycloak:
    extends:
      file: docker-compose.yml
      service: keycloak

  puppet:
    extends:
      file: docker-compose.yml
      service: puppet

  smoothness:
    extends:
      file: docker-compose.yml
      service: smoothness
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: local-src
    volumes:
      - ./docker/wildfly/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./docker/wildfly/setup.sh:/setup.sh
      - ./docker/wildfly/redeploy.sh:/redepoy.sh
      - ./run/wildfly/standalone/deployments:/opt/jboss/wildfly/standalone/staging