ARG BUILD_IMAGE=gradle:7.4-jdk17
ARG RUN_IMAGE=slominskir/smoothness:latest
ARG KEYCLOAK_SERVER=keycloak:8080
ARG LOGBOOK_SERVER=elog
ARG PUPPET_SHOW_SERVER=puppet:3000
ARG ORACLE_SERVER=oracle:1521
ARG DB_USER=SMOOTHNESS_OWNER
ARG DB_PASS=password
ARG DB_SERVICE=xepdb1
ARG DATASOURCE_NAME=smoothness
ARG WAR=smoothness-demo.war
ARG SECRET=9AubPamv1H9fAWo0q239EP7wPuH5ihb7
ARG REALM=test-realm
ARG RESOURCE=smoothness
ARG WILDFLY_USER=admin
ARG WILDFLY_PASSWORD=admin

################## Stage 0
FROM ${BUILD_IMAGE} as builder
ARG CUSTOM_CRT_URL
USER root
WORKDIR /
RUN if [ -z "${CUSTOM_CRT_URL}" ] ; then echo "No custom cert needed"; else \
       wget -O /usr/local/share/ca-certificates/customcert.crt $CUSTOM_CRT_URL \
       && update-ca-certificates \
       && keytool -import -alias custom -file /usr/local/share/ca-certificates/customcert.crt -cacerts -storepass changeit -noprompt \
       && export OPTIONAL_CERT_ARG=--cert=/etc/ssl/certs/ca-certificates.crt \
    ; fi
COPY . /app
RUN cd /app && gradle build -x test --no-watch-fs $OPTIONAL_CERT_ARG

################## Stage 1
FROM ${RUN_IMAGE} as runner
COPY --from=builder /app/smoothness-demo/build/libs/* /stage