---
version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    hostname: oracle
    container_name: oracle
    environment:
      ORACLE_PASSWORD: testing
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./docker/oracle/oradata:/opt/oracle/oradata
      - ./docker/oracle/setup:/container-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /realm.json
    volumes:
      - ./docker/keycloak/realm.json:/realm.json
      - ./docker/keycloak/setup.sh:/opt/jboss/startup-scripts/setup.sh

  puppet:
    image: slominskir/puppet-show:2.1.1
    hostname: puppet
    container_name: puppet
    ports:
      - "3000:3000"

  smoothness:
    hostname: smoothness
    container_name: smoothness
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      KEYCLOAK_SERVER: 'keycloak'
      LOGBOOK_SERVER: 'elog'
      PUPPET_SHOW_SERVER: 'puppet:3000'