---
version: '3.9'

services:
  smoothness:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/wildfly/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./run/wildfly/standalone/configuration/:/opt/jboss/wildfly/standalone/configuration/
      - ./run/wildfly/standalone/deployments/:/opt/jboss/wildfly/standalone/deployments/