ARG BUILD_IMAGE=gradle:7.4-jdk17
ARG RUN_IMAGE=quay.io/wildfly/wildfly:26.1.3.Final-jdk17
ARG ORACLE_DRIVER_PATH=/ojdbc11-21.7.0.0.jar

################## Stage 0
FROM ${BUILD_IMAGE} as builder
ARG CUSTOM_CRT_URL
USER root
WORKDIR /
RUN if [ -z "${CUSTOM_CRT_URL}" ] ; then echo "No custom cert needed"; else \
       wget -O /usr/local/share/ca-certificates/customcert.crt $CUSTOM_CRT_URL \
       && update-ca-certificates \
       && keytool -import -alias custom -file /usr/local/share/ca-certificates/customcert.crt -cacerts -storepass changeit -noprompt \
       && export OPTIONAL_CERT_ARG=--cert=/etc/ssl/certs/ca-certificates.crt \
    ; fi
COPY . /app

## Let's minimize layers in final-product by organizing files into a single copy structure
RUN mkdir /unicopy \
    && cp /app/docker/weblib/TestOracleConnection.java /unicopy \
    && cp /app/docker/weblib/docker-entrypoint.sh /unicopy \
    && cp /app/docker/weblib/docker-server.env /unicopy \
    && cp /app/bash/wildfly/server-setup.sh /unicopy \
    && cp /app/bash/wildfly/provided-setup.sh /unicopy \
    && cp /app/bash/wildfly/app-setup.sh /unicopy \
    && grep gradle.rootProject.version /app/settings.gradle | tr -s ' ' | cut -d' ' -f3 | tr -d '\047' > /unicopy/version.txt

################## Stage 1
FROM ${RUN_IMAGE} as runner
ARG CUSTOM_CRT_URL
ARG INCLUDE_SMOOTH_LIB
ARG RUN_USER=jboss:jboss
ARG ORACLE_DRIVER_PATH
USER root
COPY --from=builder /unicopy /
RUN if [ -z "${CUSTOM_CRT_URL}" ] ; then echo "No custom cert needed"; else \
       curl -sS -o /etc/pki/ca-trust/source/anchors/customcert.crt $CUSTOM_CRT_URL \
       && update-ca-trust \
       && keytool -import -alias custom -file /etc/pki/ca-trust/source/anchors/customcert.crt -cacerts -storepass changeit -noprompt \
    ; fi \
    && yum install -y wget \
    && chsh -s /bin/bash jboss \
    && if [ -z "${INCLUDE_SMOOTH_LIB}" ] ; then echo "Smooth lib excluded"; else \
    echo 'Smooth lib included. This mode is not supported' \
    && SMOOTH_VER=`cat /version.txt | tr -d '\r'` \
    && echo SMOOTH_VER: $SMOOTH_VER \
    && A='GLOBAL_ADD_LIBS=' \
    && A+="'org.jlab.smoothness-weblib" \
    && A+='|https://repo1.maven.org/maven2/org/jlab/smoothness-weblib/' \
    && A+="${SMOOTH_VER}/smoothness-weblib-${SMOOTH_VER}.jar" \
    && A+='|javaee.api,org.jboss.as.web,org.keycloak.admin-client,javax.servlet.jstl.api' \
    && A+="'" \
    && echo "${A}" > /lib.env \
    && echo WILDFLY_APP_HOME=/opt/jboss/wildfly >> /lib.env \
    && echo "cat lib.env: " \
    && cat /lib.env \
    && echo EXTRA_ADD_ENV_FILE=/lib.env >> /docker-server.env \
    ; fi \
    && /server-setup.sh /docker-server.env \
    && rm -rf /opt/jboss/wildfly/standalone/configuration/standalone_xml_history
ENTRYPOINT ["/docker-entrypoint.sh"]
ENV ORACLE_DRIVER_PATH=$ORACLE_DRIVER_PATH
USER ${RUN_USER}