---
version: '3.9'

services:
  oracle:
    extends:
      file: docker-compose.deps.yml
      service: oracle

  keycloak:
    extends:
      file: docker-compose.deps.yml
      service: keycloak

  puppet:
    extends:
      file: docker-compose.deps.yml
      service: puppet

  smoothness:
    hostname: smoothness
    container_name: smoothness
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      KEYCLOAK_SERVER: 'keycloak'
      LOGBOOK_SERVER: 'elog'
      PUPPET_SHOW_SERVER: 'puppet:3000'