
CREATE TABLE MOVIE
(
	MOVIE_ID             INTEGER NOT NULL ,
	TITLE                VARCHAR2(128 CHAR) NULL ,
	RELEASE_DATE         DATE NULL ,
	DESCRIPTION          VARCHAR2(512 CHAR) NULL ,
	MPAA_RATING          VARCHAR2(5 CHAR) NULL  CONSTRAINT  MOVIE_CK1 CHECK (MPAA_RATING IN ('G', 'PG', 'PG-13', 'R', 'NC-17')),
	DURATION_MINUTES     INTEGER NULL ,
CONSTRAINT  MOVIE_PK PRIMARY KEY (MOVIE_ID)
);
