name: CD

on:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    permissions:
      contents: write
    uses: jeffersonlab/java-workflows/.github/workflows/gh-release.yaml@v2
    with:
      files: smoothness-demo/build/libs/smoothness-demo.war
    secrets: inherit

  artifact_publish:
    permissions:
      contents: read
    needs:
      - release
    uses: jeffersonlab/java-workflows/.github/workflows/maven-publish.yaml@v2
    secrets: inherit

  docs_publish:
    permissions:
      pages: write
      id-token: write
      contents: write
    needs:
      - release
    uses: jeffersonlab/java-workflows/.github/workflows/gh-pages-publish.yaml@v2
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
      folder: smoothness-weblib/build/docs
    secrets: inherit

  docker_publish:
    permissions:
      contents: read
    needs:
      - release
    uses: jeffersonlab/container-workflows/.github/workflows/docker-publish.yaml@v2
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
      images: jeffersonlab/${{ github.event.repository.name }}-demo
    secrets: inherit

  acctest_deploy:
    permissions:
      contents: read
    needs:
      - release
    uses: jeffersonlab/general-workflows/.github/workflows/jlab-deploy-app.yaml@v2
    with:
      app: smoothness-demo
      env: acctest
      ver: ${{ needs.release.outputs.semver }}
    secrets: inherit
